# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    - name: Install dependencies
      run: |
        npm install ganache-cli
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        pipx install eth-brownie
        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      env:
        WEB3_INFURA_PROJECT_ID: ${{ secrets.InfuraAPIKey }}
      run: |
        brownie test --network mainnet-fork
